# PyTorch Basics

### Some useful function for creating tensor

Pytorch is an open source machine learing library. Here are some function used while creating tensor.
- torch.rand()
- torch.chunk()
- torch.cat()
- torch.reshape()
- torch.add()

In [1]:
# Import torch and other required modules
import torch

## 1 - torch.rand()

This **torch.rand()** is used to create tensor with random value of given shape and size. 

In [2]:
# Let's create a tensor with random function and size of 5
a = torch.rand(5)
a

tensor([0.5192, 0.0066, 0.6469, 0.7260, 0.3383])

Here I have create a tensor of size 5 with random function

In [3]:
# We can use random function to create more complex tensor too.
a = torch.rand(4,3,2)
a

tensor([[[0.6018, 0.8314],
         [0.8751, 0.8248],
         [0.5557, 0.5129]],

        [[0.5708, 0.4405],
         [0.8289, 0.3748],
         [0.9002, 0.8388]],

        [[0.8813, 0.1009],
         [0.9712, 0.2614],
         [0.4092, 0.6491]],

        [[0.7026, 0.5608],
         [0.0627, 0.4723],
         [0.6451, 0.4327]]])

Here in this example i create 4 tensor of 3x2 order using same random function.

In [4]:
# We should always have to provide the shape in integer value other then integer will show us exception
a = torch.rand(3.3,2,3)

TypeError: rand() received an invalid combination of arguments - got (float, int, int), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


Here I have given shape in float 3.3 which is not acceptance in creating tensor

##  2 - torch.chunk()

This is another method to create tensor. In this function it will concatenates the sequences of tensor in the same given dimension. All sequence of tensor must have same shape.

In [5]:
a = torch.tensor([[1,2,3],[2,3,4],[5,6,7]])
a

tensor([[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]])

In [6]:
chunkedTensor = torch.chunk(a,3,1)
chunkedTensor

(tensor([[1],
         [2],
         [5]]),
 tensor([[2],
         [3],
         [6]]),
 tensor([[3],
         [4],
         [7]]))

Here I have create 3 chunk of tensor using chunk function, we can perform operation of each chunk tensor as on our need.

In [7]:
chunkedTensor[1]*chunkedTensor[2]

tensor([[ 6],
        [12],
        [42]])

Here we perform prouct operation of chunk[1] and chunk[2] tensor and get output and element wise product

In [8]:
chunkedTensor = torch.chunk(a,3,2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Here we get dimesion error due to out of range of dimension we provide as parameter

## 3 - torch.reshape()

The torch.reshape() function will return the tenor on given shape structure.

In [9]:
a = torch.tensor([[2,3,4],[4,5,1]])
a

tensor([[2, 3, 4],
        [4, 5, 1]])

In [10]:
torch.reshape(a,(3,2))

tensor([[2, 3],
        [4, 4],
        [5, 1]])

Here We have tensor a of 2x3 size and using reshape we convert it's size to 3x2 order.

In [11]:
b = torch.rand(4,4)
b

tensor([[0.3196, 0.0358, 0.3203, 0.1442],
        [0.8600, 0.7197, 0.7269, 0.3928],
        [0.5253, 0.2942, 0.4607, 0.8157],
        [0.0871, 0.0694, 0.4093, 0.6959]])

In [12]:
torch.reshape(b,(8,2))

tensor([[0.3196, 0.0358],
        [0.3203, 0.1442],
        [0.8600, 0.7197],
        [0.7269, 0.3928],
        [0.5253, 0.2942],
        [0.4607, 0.8157],
        [0.0871, 0.0694],
        [0.4093, 0.6959]])

Here I convert 4x4 order tensor to 8x2 order new tensor

In [13]:
torch.reshape(b,(2,2))

RuntimeError: shape '[2, 2]' is invalid for input of size 16

If we want to shape tensor below/up of it's total element size then it will give us exception.

## 4 - torch.cat()

This function concatenates the sequence of tensor in the given dimension.All sequence of tensor must have same shape.

In [14]:
a = torch.tensor([[3,5,6],[7,5,3],[5,9,1]])
a

tensor([[3, 5, 6],
        [7, 5, 3],
        [5, 9, 1]])

Explanation about example

In [15]:
torch.cat((a,a,a),1)

tensor([[3, 5, 6, 3, 5, 6, 3, 5, 6],
        [7, 5, 3, 7, 5, 3, 7, 5, 3],
        [5, 9, 1, 5, 9, 1, 5, 9, 1]])

Here using 3x3 order tensor I have generate 3x9 order new tensor of dim=1

In [16]:
b = torch.rand(2,3)
torch.cat((b,b),1)

tensor([[0.5947, 0.9604, 0.3272, 0.5947, 0.9604, 0.3272],
        [0.7106, 0.7548, 0.4726, 0.7106, 0.7548, 0.4726]])

Here generate new tensor using cat function with dim size 1

In [17]:
torch.cat((b,b),2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

We have create 1D tensor but we pass dim=2 while concatinating so it will gives as exception

## 5 - torch.add()

This function will used to add some scalar value to existing tensor.

In [18]:
a = torch.tensor([[3,6,7,1],[2,5,1,8]])
a

tensor([[3, 6, 7, 1],
        [2, 5, 1, 8]])

In [19]:
torch.add(a,20)

tensor([[23, 26, 27, 21],
        [22, 25, 21, 28]])

Here I have add 20 to each element to tensor a

In [20]:
b = torch.randn(4)
torch.add(b,-10)

tensor([-9.0412, -9.3194, -9.6650, -8.9716])

Here I have add -10 to each element of b tensor.

## Tensor Gradients

PyTorch is powerful because it can compute the derivative of the tensor which has **requires_grad** set to True. Here in the following example, we just create three tensors. b and c tensor have **requires_grad** set to True, which means we are computing derivative of b and c tensor.

In [21]:
a = torch.tensor(2.)
b = torch.tensor(5.,requires_grad=True)
c = torch.tensor(6.,requires_grad=True)

In [22]:
a,b,c

(tensor(2.), tensor(5., requires_grad=True), tensor(6., requires_grad=True))

### Let's compute derivate

In [23]:
result = b * a + c
result

tensor(16., grad_fn=<AddBackward0>)

We get output 16.0 from the above expression i.e. 5.0 * 2.0 + 6.0 = 16.0

In [24]:
result.backward()

Here using **.backward()** function in PyTorch it will compute derivates of result w.r.t the tensors which have **requires_grad** properties to True.

And we can see gradients:

In [25]:
print('dresult/da:',a.grad)
print('dresult/db:',b.grad)
print('dresult/dc:',c.grad)

dresult/da: None
dresult/db: tensor(2.)
dresult/dc: tensor(1.)


As we see that **dresult/da** give None value because we have create tensor a without **requires_grad** so derivative w.r.t **a** is **None**.
But in case of **b** and **c** it gives us gradient of 2.0 and 1.0 respectively.